CREATE TABLE IF NOT EXISTS phone (PhoneID SERIAL PRIMARY KEY, Phone VARCHAR(30) NOT NULL);
CREATE TABLE IF NOT EXISTS email (EmailID SERIAL PRIMARY KEY, Email VARCHAR(100) NOT NULL);

INSERT INTO phone (PhoneID, Phone) VALUES
(DEFAULT, '+7 363 33 335 33'),

INSERT INTO email (EmailID, Email) VALUES
(DEFAULT, 'lonai@list.ru');
